export interface Destination {
  id: string;
  name: string;
  state: "AP" | "Telangana";
  category: "Popular" | "Airport" | "Pilgrimage" | "Business" | "Weekend";
  distanceKm: number;
  estimatedTime: string;
  price4Seater: number;
  price7Seater: number;
  description: string;
  lat: number;
  lng: number;
  // SVG vector map relative coordinates (0-100%)
  vectorX: number;
  vectorY: number;
  isHQ?: boolean;
}

export const RAJAHMUNDRY_HQ: Destination = {
  id: "rajahmundry",
  name: "Rajahmundry (HQ)",
  state: "AP",
  category: "Popular",
  distanceKm: 0,
  estimatedTime: "0 hrs",
  price4Seater: 0,
  price7Seater: 0,
  description: "Central Hub & Headquarters of Hanuman Travels. All journeys originate or connect here.",
  lat: 17.0005,
  lng: 81.804,
  vectorX: 58,
  vectorY: 52,
  isHQ: true,
};

export const DESTINATIONS: Destination[] = [
  {
    id: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    category: "Popular",
    distanceKm: 420,
    estimatedTime: "7 hrs 30 mins",
    price4Seater: 5999,
    price7Seater: 8499,
    description: "Capital of Telangana, IT hub, and historical city connecting Hitec City, Gachibowli & RGIA Airport.",
    lat: 17.385,
    lng: 78.4867,
    vectorX: 28,
    vectorY: 46,
  },
  {
    id: "vijayawada",
    name: "Vijayawada",
    state: "AP",
    category: "Popular",
    distanceKm: 160,
    estimatedTime: "3 hrs 15 mins",
    price4Seater: 2499,
    price7Seater: 3499,
    description: "Major commercial center on the banks of Krishna River, famous for Kanaka Durga Temple.",
    lat: 16.5062,
    lng: 80.648,
    vectorX: 48,
    vectorY: 62,
  },
  {
    id: "visakhapatnam",
    name: "Visakhapatnam (Vizag)",
    state: "AP",
    category: "Popular",
    distanceKm: 190,
    estimatedTime: "3 hrs 45 mins",
    price4Seater: 2899,
    price7Seater: 3999,
    description: "The Jewel of the East Coast, featuring RK Beach, Kailasagiri, and Araku Valley access.",
    lat: 17.6868,
    lng: 83.2185,
    vectorX: 74,
    vectorY: 38,
  },
  {
    id: "tirupati",
    name: "Tirupati",
    state: "AP",
    category: "Pilgrimage",
    distanceKm: 560,
    estimatedTime: "9 hrs 30 mins",
    price4Seater: 7999,
    price7Seater: 10999,
    description: "World famous pilgrimage destination home to Lord Venkateswara Temple at Tirumala.",
    lat: 13.6288,
    lng: 79.4192,
    vectorX: 42,
    vectorY: 84,
  },
  {
    id: "warangal",
    name: "Warangal",
    state: "Telangana",
    category: "Business",
    distanceKm: 340,
    estimatedTime: "6 hrs 10 mins",
    price4Seater: 4799,
    price7Seater: 6799,
    description: "Historical Kakatiya capital, famous for Thousand Pillar Temple and Kakatiya Arch.",
    lat: 17.9689,
    lng: 79.5941,
    vectorX: 38,
    vectorY: 38,
  },
  {
    id: "kakinada",
    name: "Kakinada",
    state: "AP",
    category: "Business",
    distanceKm: 65,
    estimatedTime: "1 hr 20 mins",
    price4Seater: 1199,
    price7Seater: 1699,
    description: "Smart port city and coastal hub known for Coringa Wildlife Sanctuary and deepwater port.",
    lat: 16.9891,
    lng: 82.2475,
    vectorX: 65,
    vectorY: 50,
  },
  {
    id: "guntur",
    name: "Guntur",
    state: "AP",
    category: "Business",
    distanceKm: 195,
    estimatedTime: "3 hrs 40 mins",
    price4Seater: 2799,
    price7Seater: 3899,
    description: "Major agricultural and textile trading hub near Amaravati capital region.",
    lat: 16.3067,
    lng: 80.4365,
    vectorX: 45,
    vectorY: 66,
  },
  {
    id: "araku",
    name: "Araku Valley",
    state: "AP",
    category: "Weekend",
    distanceKm: 290,
    estimatedTime: "6 hrs 00 mins",
    price4Seater: 4299,
    price7Seater: 5999,
    description: "Picturesque hill station surrounded by Eastern Ghats, coffee plantations, and Borra Caves.",
    lat: 18.3273,
    lng: 82.8775,
    vectorX: 72,
    vectorY: 26,
  },
  {
    id: "srisailam",
    name: "Srisailam",
    state: "AP",
    category: "Pilgrimage",
    distanceKm: 380,
    estimatedTime: "7 hrs 15 mins",
    price4Seater: 5499,
    price7Seater: 7699,
    description: "Sacred Jyotirlinga temple situated in the Nallamala forest hills.",
    lat: 16.0748,
    lng: 78.8681,
    vectorX: 32,
    vectorY: 68,
  },
  {
    id: "bhadrachalam",
    name: "Bhadrachalam",
    state: "Telangana",
    category: "Pilgrimage",
    distanceKm: 180,
    estimatedTime: "3 hrs 30 mins",
    price4Seater: 2699,
    price7Seater: 3699,
    description: "Holy Lord Rama shrine located on the banks of Godavari River.",
    lat: 17.6689,
    lng: 80.8936,
    vectorX: 50,
    vectorY: 42,
  },
  {
    id: "rgia-airport",
    name: "Hyderabad RGIA Airport",
    state: "Telangana",
    category: "Airport",
    distanceKm: 440,
    estimatedTime: "7 hrs 45 mins",
    price4Seater: 6299,
    price7Seater: 8899,
    description: "Direct premium airport transfer drop to Rajiv Gandhi International Airport.",
    lat: 17.2403,
    lng: 78.4294,
    vectorX: 26,
    vectorY: 48,
  },
  {
    id: "vizag-airport",
    name: "Vizag International Airport",
    state: "AP",
    category: "Airport",
    distanceKm: 185,
    estimatedTime: "3 hrs 35 mins",
    price4Seater: 2799,
    price7Seater: 3899,
    description: "Express airport drop/pickup service to Visakhapatnam International Airport.",
    lat: 17.7215,
    lng: 83.2245,
    vectorX: 73,
    vectorY: 37,
  },
];

export const POPULAR_ROUTES = [
  { from: "Rajahmundry", to: "Hyderabad", distance: "420 km", time: "7.5 hrs", price: "₹5,999", id: "hyderabad" },
  { from: "Rajahmundry", to: "Vijayawada", distance: "160 km", time: "3.25 hrs", price: "₹2,499", id: "vijayawada" },
  { from: "Rajahmundry", to: "Visakhapatnam", distance: "190 km", time: "3.75 hrs", price: "₹2,899", id: "visakhapatnam" },
  { from: "Rajahmundry", to: "Warangal", distance: "340 km", time: "6.1 hrs", price: "₹4,799", id: "warangal" },
];
